[HER-169] Update the design of footer
NerdsComputing/hermes.web pull request #57
Opened 2021-10-06 14:16 UTC by andreea-dumitrascu

## Description
We should update the design of the footer as it is in the link: [https://xd.adobe.com/view/f1281b54-d458-42c1-b28b-7dcca2c23b31-a47b/specs/?fbclid=IwAR3x9zSAwHJJIrQaGxIQvAKjAwys50dFidZfz7ZnOpH4-rzQX-W-kQO4LVo](url)

## Releted
[HER-169](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-169)

2021-10-07 13:08 UTC, miutamihai requested changes
1. There seems to be an issue here: 
![image](https://user-images.githubusercontent.com/23569938/136389692-9b40a8f9-a108-40ed-85a6-9275b33ebe11.png)

There's some hook that's overriding your chosen background color. We should fix that.

2. Since we're touching this part of the project, let's also use Material UI's `classes` prop here:
![image](https://user-images.githubusercontent.com/23569938/136389969-d2505d3a-9d79-4649-a913-43913c791b20.png)

3. Take a look at this:
![image](https://user-images.githubusercontent.com/23569938/136390074-0fe8c550-2fc3-4451-b3dc-a4c705fbe383.png)

Why don't we put the `content.jsx` file inside the `content` folder?

2021-10-07 13:08 UTC, miutamihai commented on src/core/layout/footer/content.jsx
> +import { Link, Typography } from '@material-ui/core'
Let's reorder our imports here.

2021-10-07 16:21 UTC, andreea-dumitrascu commented on src/core/layout/footer/content.jsx
> +import { Link, Typography } from '@material-ui/core'
Done

2021-10-07 16:25 UTC, miutamihai submitted a review, later dismissed

2021-10-07 16:31 UTC, Urzica-Platon-Casian submitted a review, later dismissed

2021-10-09 14:36 UTC, Urzica-Platon-Casian approved these changes

2021-10-11 11:09 UTC, miutamihai approved these changes

2021-10-11 11:10 UTC, merged