[HER-157] Update the design of navbar
NerdsComputing/hermes.web pull request #59
Opened 2021-10-09 15:45 UTC by andreea-dumitrascu

## Description
We should update the design of the navbar as it is in the links: [Desktop](https://xd.adobe.com/view/f1281b54-d458-42c1-b28b-7dcca2c23b31-a47b/specs/?fbclid=IwAR3x9zSAwHJJIrQaGxIQvAKjAwys50dFidZfz7ZnOpH4-rzQX-W-kQO4LVo), [Tablet](https://xd.adobe.com/view/c08e8b21-5cdf-469b-9e66-2c500a5ec043-95dd/?fbclid=IwAR1x4Wn89kjsO0ZivtrxqBztZvh67ubeCMJGVc8eMmivnjwBRwteIr7zP20) ,[Phone](https://xd.adobe.com/view/c5fc8477-17c8-4014-872e-6e6575603d84-90af/?fbclid=IwAR2aCw3az4LwYWh4oYOW08rfN_9r8F8xh8u98QghtsQUYmHNQoKX8QUCAt4).

## Related
[HER-157](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-157)

2021-10-11 11:28 UTC, miutamihai requested changes
![image](https://user-images.githubusercontent.com/23569938/136782423-857c64bd-5970-4183-9eb4-bc6e4d51d451.png)
![image](https://user-images.githubusercontent.com/23569938/136782504-7db17814-1498-465f-bbf5-c38129c4697a.png)
The font weight used here does not align with the design. Let's rectify that.

![image](https://user-images.githubusercontent.com/23569938/136782647-581c3463-4d74-4c76-b050-d124546ab399.png)
Also, this probably not the expected behaviour here. Let's ditch that sticky appbar.

2021-10-11 11:28 UTC, miutamihai commented on src/core/layout/navbar/links/hooks/use-cameras-props.js
> +export const useCamerasProps = () => ({
![image](https://user-images.githubusercontent.com/23569938/136780886-ea585934-badb-45cf-824c-d8bdf43421e2.png)
All these hooks are __really__ similar. Can't we avoid all this code duplication somehow?

2021-10-11 11:28 UTC, miutamihai commented on src/core/layout/navbar/links/hooks/use-on-page.js
> +  color: '#1A856B',
Let's declare all these colors as variables in our theme.

Check their documentation on how to do that [here](https://mui.com/customization/theming/)

2021-10-11 11:28 UTC, miutamihai commented on src/core/layout/navbar/links/hooks/use-styles.js
> +  const onPage = useOnPage()
These namings are ...weird. Let's use something like `activeStyle` and `inactiveStyle`.

2021-10-11 11:28 UTC, miutamihai commented on src/core/layout/navbar/links/line.jsx
> +const onPage = { backgroundColor: '#1A856B', height: 1, marginLeft: 4, width: '100%' }
Same here.

2021-10-11 11:28 UTC, miutamihai commented on src/core/layout/navbar/links/line.jsx
> +export const Line = ({ path }) => {
Actually, why create a separate component for the line under when we can just apply css for that?

2021-10-11 11:28 UTC, miutamihai commented on src/core/layout/navbar/logo/logo-desktop.jsx
> +export const LogoDesktop = () => <Material.Grid item>
![image](https://user-images.githubusercontent.com/23569938/136781858-8e8754ae-4d8b-4dc9-b44d-cdbc200e21a2.png)
These two components are identical... Do we really need to duplicate them?

2021-10-11 12:05 UTC, andreea-dumitrascu commented on src/core/layout/navbar/links/hooks/use-cameras-props.js
> +export const useCamerasProps = () => ({
Done.

2021-10-11 12:09 UTC, andreea-dumitrascu commented on src/core/layout/navbar/links/hooks/use-styles.js
> +  const onPage = useOnPage()
Done

2021-10-11 13:07 UTC, andreea-dumitrascu commented on src/core/layout/navbar/links/hooks/use-on-page.js
> +  color: '#1A856B',
Done

2021-10-11 14:40 UTC, andreea-dumitrascu commented on src/core/layout/navbar/logo/logo-desktop.jsx
> +export const LogoDesktop = () => <Material.Grid item>
Done

2021-10-12 11:40 UTC, andreea-dumitrascu commented on src/core/layout/navbar/links/line.jsx
> +const onPage = { backgroundColor: '#1A856B', height: 1, marginLeft: 4, width: '100%' }
Done

2021-10-12 11:40 UTC, andreea-dumitrascu commented on src/core/layout/navbar/links/line.jsx
> +export const Line = ({ path }) => {
Done

2021-10-12 12:54 UTC, mihairadulescu commented
add 

`
    position: sticky;
    background: white;
 `
 
     
![image](https://user-images.githubusercontent.com/11047826/136960107-843b3170-4404-49a7-8c2a-12f03ac2527f.png)

2021-10-12 12:54 UTC, mihairadulescu commented
add 

```
    position: sticky;
    background: white;
    ```
    
    and it should be like
    
    
![image](https://user-images.githubusercontent.com/11047826/136960107-843b3170-4404-49a7-8c2a-12f03ac2527f.png)

2021-10-12 13:12 UTC, andreea-dumitrascu commented
> background: white

Done.

2021-10-12 13:18 UTC, mihairadulescu approved these changes

2021-10-12 13:18 UTC, mihairadulescu commented on src/core/layout/navbar/logo/hooks/use-img-props.js
> +  ...useClassName(),
className:useClassName() would  be better,.

2021-10-12 13:19 UTC, mihairadulescu commented
Cool! Redeploying.

2021-10-12 13:24 UTC, miutamihai approved these changes

2021-10-12 13:31 UTC, merged