[HER-170] Update the first section of the home page
NerdsComputing/hermes.web pull request #60
Opened 2021-10-14 17:01 UTC by andreea-dumitrascu

## Description
We should update the design of the first section from the home page as shown in the links: [Desktop](https://xd.adobe.com/view/f1281b54-d458-42c1-b28b-7dcca2c23b31-a47b/specs/?fbclid=IwAR3x9zSAwHJJIrQaGxIQvAKjAwys50dFidZfz7ZnOpH4-rzQX-W-kQO4LVo), [Tablet](https://xd.adobe.com/view/c08e8b21-5cdf-469b-9e66-2c500a5ec043-95dd/?fbclid=IwAR1x4Wn89kjsO0ZivtrxqBztZvh67ubeCMJGVc8eMmivnjwBRwteIr7zP20), [Smartphone](https://xd.adobe.com/view/c5fc8477-17c8-4014-872e-6e6575603d84-90af/?fbclid=IwAR2aCw3az4LwYWh4oYOW08rfN_9r8F8xh8u98QghtsQUYmHNQoKX8QUCAt4)

## Related
[HER-170](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-170)

2021-10-14 17:43 UTC, miutamihai requested changes

2021-10-14 17:43 UTC, miutamihai commented on src/home/first-section/description/style.js
> +  color: theme.palette.primary.main,
Let's not import the theme from its folder. Instead, the `makeStyle` function can also receive a callback as its parameter, a callback which handly has the theme as its one and only parameter.
Thusly, your style would become something like this:
```js
export const useStyle = makeStyle(theme => ({
    fontSize: '16px',
    color: theme.palette.primary.main,
}))
```

2021-10-14 17:43 UTC, miutamihai commented on src/home/first-section/link/content.jsx
> +  <p className={useStyle().contentFirst}>Git clone </p>
I know the design says so, but since the `git` command is lowercase, let's have it lowercase here too.

2021-10-14 17:43 UTC, miutamihai commented on src/home/first-section/link/style.js
> +export const useStyle = makeStyles({ title, contentFirst, contentSecond })
1. Let's rename this file to `use-style.js`
2. Let's use the theme callback here too.

2021-10-14 17:43 UTC, miutamihai commented on src/home/first-section/live/buttons/hooks/use-cameras-style.js
> +export const useCamerasStyle = makeStyles({ root })
Same here.

2021-10-14 17:43 UTC, miutamihai commented on src/home/first-section/live/buttons/hooks/use-detections-style.js
> +export const useDetectionsStyle = makeStyles({ root })
Same here.

2021-10-14 17:43 UTC, miutamihai commented on src/home/first-section/live/buttons/see-detections.jsx
> +export const SeeDetections = () => <Grid item>
![image](https://user-images.githubusercontent.com/23569938/137368805-011a8838-7203-4531-8294-1c3502726533.png)
These two components are very similar. Can we merge them into a common component somehow?

2021-10-14 17:43 UTC, miutamihai commented on src/home/first-section/title/style.js
> +export const useStyle = makeStyles({ head })
1. Rename again
2. Use theme callback again

2021-10-14 17:43 UTC, miutamihai commented on src/home/content.jsx
> +  <Grid item justify={'left'} style={{ padding: '0 15% 0 15%' }}>
Let's avoid using inline styles.

2021-10-15 09:36 UTC, andreea-dumitrascu commented on src/home/first-section/link/content.jsx
> +  <p className={useStyle().contentFirst}>Git clone </p>
Done

2021-10-15 10:07 UTC, andreea-dumitrascu commented on src/home/first-section/description/style.js
> +  color: theme.palette.primary.main,
Done

2021-10-15 10:35 UTC, andreea-dumitrascu commented on src/home/first-section/link/style.js
> +export const useStyle = makeStyles({ title, contentFirst, contentSecond })
Done

2021-10-15 10:39 UTC, andreea-dumitrascu commented on src/home/first-section/title/style.js
> +export const useStyle = makeStyles({ head })
Done

2021-10-15 10:43 UTC, andreea-dumitrascu commented on src/home/content.jsx
> +  <Grid item justify={'left'} style={{ padding: '0 15% 0 15%' }}>
Done

2021-10-15 11:27 UTC, andreea-dumitrascu commented on src/home/first-section/live/buttons/see-detections.jsx
> +export const SeeDetections = () => <Grid item>
Done

2021-10-15 13:33 UTC, miutamihai requested changes
1. 
![image](https://user-images.githubusercontent.com/23569938/137495156-29e099f2-ebe5-4113-a7a9-417d38663db2.png)
Let's rename this to something like `HeadingSection` 
2. 
![image](https://user-images.githubusercontent.com/23569938/137495303-74e856c6-80bf-40c5-9c3d-a900178cd8d2.png)
Let's change this folder's name to match with its exported file
3. 
![image](https://user-images.githubusercontent.com/23569938/137495413-ff34cb34-e668-4830-b8fc-3b2614816ed0.png)
Let's change this
4. 
![image](https://user-images.githubusercontent.com/23569938/137495516-be2dc922-6b22-4fa9-a437-d4b58bc06ca5.png)
And also this

2021-10-15 13:33 UTC, miutamihai commented on src/home/first-section/description/index.jsx
> +    <p className={useStyle().root}>
Let's use Material-UI's typography component here, with the p variant. Thusly, we can pass the styles using the classes prop.

2021-10-15 13:33 UTC, miutamihai commented on src/home/first-section/link/content.jsx
> +  <p className={useContentFirstStyle().root}>git clone </p>
Same applies to these.

2021-10-15 13:33 UTC, miutamihai commented on src/home/first-section/title/index.jsx
> +  <h1 className={useStyle().root}>Hermes, we build the world</h1>
Here too.

2021-10-15 13:33 UTC, miutamihai commented on src/home/first-section/live/buttons/hooks/use-button-style.js
> +  console.log(path)
Extra log much?

2021-10-15 14:12 UTC, andreea-dumitrascu commented on src/home/first-section/description/index.jsx
> +    <p className={useStyle().root}>
Done

2021-10-15 14:20 UTC, andreea-dumitrascu commented on src/home/first-section/link/content.jsx
> +  <p className={useContentFirstStyle().root}>git clone </p>
Done

2021-10-15 14:33 UTC, andreea-dumitrascu commented on src/home/first-section/title/index.jsx
> +  <h1 className={useStyle().root}>Hermes, we build the world</h1>
Done

2021-10-15 14:33 UTC, andreea-dumitrascu commented on src/home/first-section/live/buttons/hooks/use-button-style.js
> +  console.log(path)
Done

2021-10-15 15:41 UTC, miutamihai commented on src/home/first-section/description/index.jsx
> +    <p className={useStyle().root}>
Let's use the classes prop here.

2021-10-15 15:45 UTC, miutamihai requested changes
![image](https://user-images.githubusercontent.com/23569938/137515630-b8d6f13f-5fb1-4851-bace-b710c439d259.png)
Let's also rename this file to index.js


![image](https://user-images.githubusercontent.com/23569938/137515738-5b9cac94-6309-4ab9-aec8-d2ea84668704.png)
Also, let's rename this folder to match this component's name

2021-10-15 15:58 UTC, andreea-dumitrascu commented
> ![image](https://user-images.githubusercontent.com/23569938/137515630-b8d6f13f-5fb1-4851-bace-b710c439d259.png) Let's also rename this file to index.js
> 
> ![image](https://user-images.githubusercontent.com/23569938/137515738-5b9cac94-6309-4ab9-aec8-d2ea84668704.png) Also, let's rename this folder to match this component's name

Done

2021-10-17 08:57 UTC, miutamihai approved these changes

2021-10-18 10:51 UTC, Urzica-Platon-Casian approved these changes
Nois👍

2021-10-18 11:29 UTC, merged