[HER-171] Update the design of the characters section
NerdsComputing/hermes.web pull request #61
Opened 2021-10-19 17:39 UTC by andreea-dumitrascu

## Description
We should add on the home page the design for two characters that are displayed in parallel like in the photo: 
![image](https://user-images.githubusercontent.com/72592844/137962583-0a5902dd-b51f-4524-8c1b-7514d6cd3c0b.png)
[Desktop](https://xd.adobe.com/view/f1281b54-d458-42c1-b28b-7dcca2c23b31-a47b/specs/?fbclid=IwAR3x9zSAwHJJIrQaGxIQvAKjAwys50dFidZfz7ZnOpH4-rzQX-W-kQO4LVo), [Tablet](https://xd.adobe.com/view/c08e8b21-5cdf-469b-9e66-2c500a5ec043-95dd/?fbclid=IwAR1x4Wn89kjsO0ZivtrxqBztZvh67ubeCMJGVc8eMmivnjwBRwteIr7zP20), [Phone](https://xd.adobe.com/view/c5fc8477-17c8-4014-872e-6e6575603d84-90af/?fbclid=IwAR2aCw3az4LwYWh4oYOW08rfN_9r8F8xh8u98QghtsQUYmHNQoKX8QUCAt4)

## Related
[HER-171](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-171)

2021-10-20 08:08 UTC, miutamihai requested changes
![image](https://user-images.githubusercontent.com/23569938/138053576-3fbf1e2b-a151-4702-8eb2-0537f9240500.png)
Let's replace these placeholders with simple fixed sized divs having the required css.

2021-10-20 08:08 UTC, miutamihai commented on src/home/character-section/hooks/use-class-name.js
> +  return ({ className: position === 'left' ? style.left : style.right })
Instead of returning an object containing a field called `className`, why don't we return just the className here?

2021-10-20 08:08 UTC, miutamihai commented on src/home/character-section/hooks/use-character-title-style.js
> +    [theme.breakpoints.up('xs')]: { ...desktop },
Using the spread operator for a single object field is overkill. At this point, we're adding complexity to our code instead of reducing it. Why not pass in the __value__ we need directly?

2021-10-20 08:08 UTC, miutamihai commented on src/home/character-section/hooks/use-character-title-style.js
> +    [theme.breakpoints.down('xs')]: { ...phone },
Same here.

2021-10-20 08:08 UTC, miutamihai commented on src/home/character-section/hooks/use-descripiton-style.js
> +    [theme.breakpoints.up('xs')]: { ...desktop },
Same here.

2021-10-20 08:08 UTC, miutamihai commented on src/home/character-section/hooks/use-descripiton-style.js
> +    [theme.breakpoints.up('xs')]: { ...desktop },
Also there's a typo in the file name.

2021-10-20 08:08 UTC, miutamihai commented on src/home/character-section/hooks/use-left-style.js
> +const desktop = ({
![image](https://user-images.githubusercontent.com/23569938/138052809-2cb0a983-c5ff-4b60-8f38-484f5f08a09c.png)
These two files are identical with the exception of the `marginLeft` prop. Could we merge them somehow?

2021-10-20 08:08 UTC, miutamihai commented on src/home/character-section/styles.js
> +  borderRight: `5px solid ${theme.palette.secondary.main}`,
We've talked previously about importing the `theme` directly. Let's fix this.

2021-10-20 11:24 UTC, miutamihai commented on src/home/character-section/hooks/use-class-name.js
> +  return ({ className: position === 'left' ? style.left : style.right })
Also, it should be `future` instead of `feature` characters.

2021-10-21 11:54 UTC, ConstantinescuAndrei commented on src/home/character-section/hooks/use-class-name.js
> +  return ({ className: position === 'left' ? style.left : style.right })
Done

2021-10-21 11:54 UTC, ConstantinescuAndrei commented on src/home/character-section/hooks/use-character-title-style.js
> +    [theme.breakpoints.up('xs')]: { ...desktop },
Done

2021-10-21 11:54 UTC, ConstantinescuAndrei commented on src/home/character-section/hooks/use-character-title-style.js
> +    [theme.breakpoints.down('xs')]: { ...phone },
Done

2021-10-21 11:54 UTC, ConstantinescuAndrei commented on src/home/character-section/hooks/use-descripiton-style.js
> +    [theme.breakpoints.up('xs')]: { ...desktop },
Done

2021-10-21 11:54 UTC, ConstantinescuAndrei commented on src/home/character-section/hooks/use-left-style.js
> +const desktop = ({
Done

2021-10-21 11:54 UTC, ConstantinescuAndrei commented on src/home/character-section/styles.js
> +  borderRight: `5px solid ${theme.palette.secondary.main}`,
Done

2021-10-21 12:08 UTC, miutamihai commented on src/home/character-section/hooks/use-class-name.js
> +  return ({ className: position === 'left' ? style.left : style.right })
No, it's not.

2021-10-21 12:10 UTC, miutamihai commented on src/home/character-section/styles.js
> +  borderRight: `5px solid ${theme.palette.secondary.main}`,
![image](https://user-images.githubusercontent.com/23569938/138274386-e5c51b1a-5208-4259-9e61-e08dd3be25fc.png)
Let's rename this `create` function to something like `makeForVariant` or `styleForVariant`.

2021-10-21 13:49 UTC, miutamihai approved these changes

2021-10-21 13:50 UTC, Urzica-Platon-Casian approved these changes
Nois

2021-10-21 14:05 UTC, merged