[HER-173] Update design of the map from the cameras page
NerdsComputing/hermes.web pull request #64
Opened 2021-10-25 14:52 UTC by ConstantinescuAndrei

## Description
Update the design of the map based of the following links:
- [Desktop](https://xd.adobe.com/view/f1281b54-d458-42c1-b28b-7dcca2c23b31-a47b/screen/d4112a22-e142-415f-bd98-4ae1844cf3b9/?fbclid=IwAR3x9zSAwHJJIrQaGxIQvAKjAwys50dFidZfz7ZnOpH4-rzQX-W-kQO4LVo)
- [Tablet](https://xd.adobe.com/view/c08e8b21-5cdf-469b-9e66-2c500a5ec043-95dd/screen/2a4a77a7-7d58-4e0c-a4d6-e6dba32384b0/specs/?fbclid=IwAR1x4Wn89kjsO0ZivtrxqBztZvh67ubeCMJGVc8eMmivnjwBRwteIr7zP20)
- [Smartphone](https://xd.adobe.com/view/c5fc8477-17c8-4014-872e-6e6575603d84-90af/screen/863da6bd-3b24-4a0c-807d-d60878312520/specs/?fbclid=IwAR2aCw3az4LwYWh4oYOW08rfN_9r8F8xh8u98QghtsQUYmHNQoKX8QUCAt4)

## Related
[HER-173](https://nerds-interns.atlassian.net/browse/HER-173)

2021-10-25 17:35 UTC, miutamihai requested changes

2021-10-25 17:35 UTC, miutamihai commented on src/cameras/map/sidebar/content/search/hooks/use-searchbar-style.js
> +  border: '1px solid #0000001F',
Let's extract this color to the theme.

2021-10-25 17:35 UTC, miutamihai commented on src/cameras/map/sidebar/header/expand/styles/mobile-styles.js
> +import { makeStyles } from '@material-ui/core'
![image](https://user-images.githubusercontent.com/23569938/138742995-09495bef-568a-47b2-ada2-1fb0a0e9b832.png)
Can't we somehow combine these two?

2021-10-26 13:01 UTC, ConstantinescuAndrei commented on src/cameras/map/sidebar/content/search/hooks/use-searchbar-style.js
> +  border: '1px solid #0000001F',
Done

2021-10-26 13:01 UTC, ConstantinescuAndrei commented on src/cameras/map/sidebar/header/expand/styles/mobile-styles.js
> +import { makeStyles } from '@material-ui/core'
Done

2021-10-26 13:02 UTC, miutamihai approved these changes

2021-10-26 13:10 UTC, merged